import dataclasses
from collections.abc import Iterable
from dataclasses import Field
from typing import Any, TypeVar

from sowing import Node, traversal

from .signature import Operator, Signature, make_checked_operator

CandidateNode = Node[tuple[Any, ...], None]
null_node = CandidateNode(("null",))
choose_node = CandidateNode(("choose",))


def _is_null(node: CandidateNode) -> bool:
    return node.data == null_node.data


def _is_choose(node: CandidateNode) -> bool:
    return node.data == choose_node.data


def _children(node: CandidateNode) -> tuple[CandidateNode, ...]:
    return tuple(edge.node for edge in node.edges)


def _single_choose(left: CandidateNode, right: CandidateNode) -> CandidateNode:
    return right if _is_null(left) else left


def _all_choose(left: CandidateNode, right: CandidateNode) -> CandidateNode:
    # Flatten nested choice operators and remove nulls
    nodes = tuple(
        child_node
        for child_nodes in (
            _children(child) if _is_choose(child) else (child,)
            for child in (left, right)
        )
        for child_node in child_nodes
        if not _is_null(child_node)
    )

    # Remove duplicate edges and put them in canonical order
    nodes = tuple(sorted(set(nodes), key=str))

    if len(nodes) == 0:
        return null_node
    elif len(nodes) == 1:
        return nodes[0]
    else:
        return choose_node.extend(nodes)


def _trace_operator(field: Field) -> Operator[Any]:
    def operator(
        args: tuple[Any, ...],
        args_types: tuple[type[Any], ...],
    ) -> CandidateNode:
        root: CandidateNode = Node((field.name,))

        for arg_type, arg_value in zip(args_types, args, strict=True):
            if isinstance(arg_type, TypeVar):
                # Make null element absorbent in combinations
                if _is_null(arg_value):
                    return null_node

                root = root.add(arg_value)
            else:
                root = root.replace(data=root.data + (arg_value,))

        return root

    return operator


def trace[S: Signature[Any]](signature: type[S], single=True) -> S:
    """
    Derive an algebra that produces candidates from a signature.

    Each call to an algebra operator creates a node which is connected to its arguments,
    creating a tree of candidates. When :param:`single` is True, a single tree
    representing the first candidate is produced. When :param:`single` is False, choice
    nodes are inserted to create a graph which succinctly represents all candidates.

    Note: The return type should be 'S[CandidateNode]'. Unfortunately, Python’s type
    system is not powerful enough to express this yet (see
    <https://github.com/python/typing/issues/548>).

    :param signature: signature from which to derive the algebra
    :param single: whether to produce a tree for a single candidate (if True, the
        default), or to include choice nodes to represent all candidates (if False)
    :returns: created algebra
    """
    elements = {
        field.name: make_checked_operator(
            field.type,
            Node,
            _trace_operator(field),
        )
        for field in dataclasses.fields(signature)
    }
    elements["choose"] = _single_choose if single else _all_choose
    return signature(**elements)


def lazyproduct(*args: Iterable[Any]) -> Iterable[tuple]:
    """
    Lazy-evaluation equivalent to `itertools.product`.

    The standard `product` helper starts by fully evaluating its arguments and storing
    them in tuples, before yielding the first value. For long iterables, this causes a
    delay before the first result appears.
    """
    if not args:
        yield ()
    else:
        first = True
        saved = []

        for arg in args[0]:
            if first:
                for item in lazyproduct(*args[1:]):
                    saved.append(item)
                    yield (arg,) + item

                first = False
            else:
                for item in saved:
                    yield (arg,) + item


def enumerate_candidates(root: CandidateNode) -> Iterable[CandidateNode]:
    """
    Enumerate all candidate subtrees from a candidate graph.

    Given a candidate graph, which may be generated by using :func:`trace` with
    :param:`single` set to False, this function recursively traverses the graph and
    yields all candidate subtrees.

    While the number of candidate subtrees may be exponential in the size of the
    original graph, this function only needs linear time and memory to go from a
    candidate to the next.

    The results are identical to using the powerset of a trace algebra, but it does not
    require exponential memory as the individual candidates are generated on the fly.

    :param root: root of the candidate graph to traverse
    :returns: iterator over all candidate subtrees
    """
    if _is_null(root):
        return

    if _is_choose(root):
        for child in _children(root):
            yield from enumerate_candidates(child)

        return

    for children in lazyproduct(
        *(enumerate_candidates(child) for child in _children(root))
    ):
        yield CandidateNode(root.data).extend(children)


default_choose_node_style = {
    "label": "+",
    "shape": "square",
    "style": "filled",
    "fillcolor": "lightgray",
    "height": "0",
}
default_node_style = {"shape": "box", "style": "rounded", "ordering": "out"}


def graph_to_dot(
    root: CandidateNode,
    choose_style: dict[str, str] = default_choose_node_style,
    default_style: dict[str, str] = default_node_style,
    **graph_attributes: dict[str, str],
) -> str:
    """Create a representation of a signature call graph in DOT format."""

    lines = ["digraph {"]
    for key, value in graph_attributes.items():
        lines.append(f'  {key}="{value}";')
    escape_rules = str.maketrans({'"': r"\""})
    ids: dict[CandidateNode, int] = {}

    def visit(node):
        if node not in ids:
            ids[node] = len(ids)

    for cursor in traversal.depth(root, unique=True):
        source = cursor.node
        assert source is not None
        visit(source)

        head, *args = source.data
        label = f"{head}({', '.join(map(repr, args))})" if args else head

        style = {"label": label}
        style = style | (choose_style if _is_choose(source) else default_style)
        attrs = ", ".join(
            f'{key}="{value.translate(escape_rules)}"' for key, value in style.items()
        )
        lines.append(f"{ids[source]} [{attrs}]")

        for edge in source.edges:
            target = edge.node
            visit(target)
            lines.append(f"{ids[source]} -> {ids[target]}")

    lines.append("}")
    return "\n".join(lines)
