import dataclasses
from collections.abc import Iterable
from dataclasses import dataclass
from functools import partial
from typing import Any, TypeVar

from sowing import Node, traversal

from .signature import Signature, make_checked_operator


@dataclass(frozen=True)
class CircuitData:
    """Data attached to a node of an algebraic circuit."""

    # Name of the operator associated to the node
    operator: str

    # List of outdomain arguments for the operator
    args: tuple[Any, ...] = ()


type Circuit = Node[CircuitData, None]


def make_circuit_node(*args, **kwargs) -> Circuit:
    """Create an algebraic circuit node."""
    return Node(CircuitData(*args, **kwargs))


def _is_null(node: Circuit) -> bool:
    return node.data.operator == "null"


def _is_choose(node: Circuit) -> bool:
    return node.data.operator == "choose"


def _children(node: Circuit) -> tuple[Circuit, ...]:
    return tuple(edge.node for edge in node.edges)


def _choose_operator(left: Circuit, right: Circuit) -> Circuit:
    # Flatten nested choice operators and remove nulls
    nodes = tuple(
        child_node
        for child_nodes in (
            _children(child) if _is_choose(child) else (child,)
            for child in (left, right)
        )
        for child_node in child_nodes
        if not _is_null(child_node)
    )

    # Remove duplicate edges
    nodes = tuple(dict.fromkeys(nodes).keys())

    if len(nodes) == 0:
        return make_circuit_node(operator="null")
    elif len(nodes) == 1:
        return nodes[0]
    else:
        return make_circuit_node(operator="choose").extend(nodes)


def _trace_operator(
    name: str,
    args: tuple[Any, ...],
    args_types: tuple[type[Any], ...],
) -> Circuit:
    child_args: list[Circuit] = []
    out_args = []

    for arg_type, arg_value in zip(args_types, args, strict=True):
        if isinstance(arg_type, TypeVar):
            # Make null element absorbent in combinations
            if _is_null(arg_value):
                return arg_value

            child_args.append(arg_value)
        else:
            out_args.append(arg_value)

    return make_circuit_node(operator=name, args=tuple(out_args)).extend(child_args)


def trace[S: Signature[Any]](signature: type[S]) -> S:
    """
    Derive an algebra that produces algebraic circuits from a signature.

    Each call to an algebra operator creates a node which is connected to its arguments,
    creating a circuit of solutions. The resulting circuits may be passed to the
    :func:`enumerate_solutions` and :func:`get_solution` to retrieve the solutions.

    Note: The return type should be 'S[CircuitData]'. Unfortunately, Python’s type
    system is not powerful enough to express this yet (see
    <https://github.com/python/typing/issues/548>).

    :param signature: signature from which to derive the algebra
    :returns: created algebra
    """
    elements = {
        field.name: make_checked_operator(
            field.type,
            Node,
            partial(_trace_operator, field.name),
        )
        for field in dataclasses.fields(signature)
    }
    elements["choose"] = _choose_operator
    return signature(**elements)


def lazyproduct(*args: Iterable[Any]) -> Iterable[tuple]:
    """
    Lazy-evaluation equivalent to `itertools.product`.

    The standard `product` helper starts by fully evaluating its arguments and storing
    them in tuples, before yielding the first value. For long iterables, this causes a
    delay before the first result appears.
    """
    if not args:
        yield ()
    else:
        first = True
        saved = []

        for arg in args[0]:
            if first:
                for item in lazyproduct(*args[1:]):
                    saved.append(item)
                    yield (arg,) + item

                first = False
            else:
                for item in saved:
                    yield (arg,) + item


def enumerate_solutions(root: Circuit) -> Iterable[Circuit]:
    """
    Enumerate all solutions from a circuit.

    Given a circuit, which may be generated by using :func:`trace`, this function
    successively yields all the solutions represented by the circuit.

    While the number of solutions may be exponential in the size of the original
    circuit, this function only needs linear time and memory to go from a circuit
    to the next.

    The results are identical to using the powerset of a trace algebra, but it does not
    require exponential memory as the individual solutions are generated on the fly.

    :param root: root of the circuit to traverse
    :returns: iterator over all solutions
    """
    if _is_null(root):
        return

    if _is_choose(root):
        for child in _children(root):
            yield from enumerate_solutions(child)

        return

    for children in lazyproduct(
        *(enumerate_solutions(child) for child in _children(root))
    ):
        yield Node(root.data).extend(children)


def get_solution(circuit: Circuit) -> Circuit:
    """
    Extract a solution from a circuit.

    Given a circuit, which may be generated by using :func:`trace`, this function
    retrieves an arbitrary solution represented by the circuit.

    :param circuit: circuit to traverse
    :returns: solution subcircuit
    """
    return next(iter(enumerate_solutions(circuit)))


def graph_to_dot(root: Circuit) -> str:
    """Create a representation of a signature call graph in DOT format."""
    # Appearance of choice nodes
    choose_style = {
        "label": "+",
        "shape": "square",
        "style": "filled",
        "fillcolor": "lightgray",
        "height": "0",
    }

    # Appearance of all other nodes
    default_style = {
        "shape": "box",
        "style": "rounded",
        "ordering": "out",  # ensure left-to-right order of outgoing edges is preserved
    }

    lines = ["digraph {"]
    escape_rules = str.maketrans({'"': r"\""})
    ids: dict[Circuit, int] = {}

    def visit(node):
        if node not in ids:
            ids[node] = len(ids)

    for cursor in traversal.depth(root, unique=True):
        source = cursor.node
        assert source is not None
        visit(source)

        head = source.data.operator
        args = source.data.args
        label = f"{head}({', '.join(map(repr, args))})" if args else head

        style = {"label": label}
        style = style | (choose_style if _is_choose(source) else default_style)
        attrs = ", ".join(
            f'{key}="{value.translate(escape_rules)}"' for key, value in style.items()
        )
        lines.append(f"{ids[source]} [{attrs}]")

        for edge in source.edges:
            target = edge.node
            visit(target)
            lines.append(f"{ids[source]} -> {ids[target]}")

    lines.append("}")
    return "\n".join(lines)
